Server:
  port: 8080
cors:
  originPatterns: http://localhost:5173,http://localhost:5174
security:
  jwt:
    token:
      secret-key: 44fr37@3$
      expire-lenght: 360000
file:
  upload-dir: /home/abe/storage
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    username:
    password:
spring:
  application:
    name: conecta-uniesp
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/conecta-uniesp
    username: postgre
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
springdoc:
  pathsToMatch: /**
  swagger-ui:
    use-root-path: true
  servelet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
